### ISSUE TITLE
Retrieve Auto-Swap Subscriptions for a Given Wallet Address

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-backend#15]
Currently, users can create auto-swap subscriptions, but there is no way for them to view or manage their existing subscriptions. This creates a poor user experience and makes it difficult for users to track their swap subscriptions.

**Task:**

Implement a new service endpoint that allows a connected wallet address to retrieve a list of their active auto-swap subscriptions. This endpoint should return relevant subscription details, such as:

- From Token
- To Token
- Percentage
- Status (is_active)

**Comment by Michaelkingsdev** [comment]
I'd like to handle this task.

**Comment by Jagadeeshftw** [comment]
I’d like to help with this.

**Comment by 1nonlypiece** [comment]
I'd like to take this issue.

**Comment by mimisavage** [comment]
Let me handle this issue!

**Comment by caxtonacollins** [comment]
May I try my hand at this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Supa-mega** [comment]
Is it okay if I take this?

**Comment by codebestia** [comment]
I’d like to work on this.
ETA - 1 day

**Comment by sprtd** [comment]
@BrunoAmbricca Any update with this issue?

**Comment by emarc99** [comment]
I have gone through your `src/http/subscription.rs`.
I can do it ETA 3 days

**Comment by Birdmannn** [comment]
Hello Dev, can I handler this, I'm good in rust and creating RESTful backend services. I can create this new endpoint. I'll do it before the hack ends next tomorrow

**Comment by GideonBature** [comment]
Greetings, I am a Software Engineer with experience in Rust writing RESTful API Endpoints. If assigned, I will send my first PR within 48 hrs.

Thank you!

**Comment by sprtd** [comment]
@codebestia Would you like to give this a try?
