### ISSUE TITLE
Implement Subscription Service for Auto-Swap

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-backend#2]
## Overview

This service processes subscription events emitted when a user opts into the auto-swap feature. It records the user's preferences for swapping tokens automatically.

## Payload

The service should handle incoming payloads with the following structure:

- `wallet_address` : The user's wallet address.
- `to_token` : The stable token they want to swap to.
- `from_token` (array of token_addresses): Tokens they want to swap from.
- `percentage` (array of numbers): Corresponding percentages for each from_token.

## Functionality

1. **Create Subscription**:
    - Store the user's subscription in the `swap_subscription` table with:
        - `wallet_address`
        - `to_token`

2. **Populate Token-Specific Data:**
    - For each `from_token`, store the token and its swap `percentage` in the `swap_subscription_from_token` table.

**Acceptance Criteria**

- Subscriptions are saved correctly for each user in the database.
- `from_token` and `percentage` arrays align properly (e.g., 50% for STRK, 50% for another token).

### Examples

**Input Payload:**

```json
{
  "wallet_address": "0xUserAddress",
  "to_token": "USDT",
  "from_token": ["STRK", "DAI"],
  "percentage": [50, 50]
}
```
**Database Updates:**

- `swap_subscription`:
    - `wallet_address`: 0xUserAddress
    - `to_token`: USDT
- `swap_subscription_from_token`:
    - `from_token`: STRK, `percentage`: 50
    - `from_token`: BROTHER, `percentage`: 50

#### Dependencies
- Subscription event from the smart contract.
- Database tables: swap_subscription, swap_subscription_from_token.

**Comment by 0xdevcollins** [comment]
I'd like to take this issue.

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by GideonBature** [comment]
Can I take care of this issue?

my name is Gideon Bature, a Software Engineer with experience working on Rust projects. If assigned this task, will send my first PR within 48 hours.

Thank you!

**Comment by mimisavage** [comment]
Can I be assigned to this?

**Comment by CEOliam** [comment]
Is it okay if I take this?

**Comment by Michaelkingsdev** [comment]
I'd love to work on this!

**Comment by Benjtalkshow** [comment]
Can I tackle this one?

**Comment by vestor-dev** [comment]
Can I start working on this?
@Abeeujah please kindly assign

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `kakarot-ssj`
- `ef-tests`
- `Raito`
- `Starknet-Phone`
- `Madara`
- `stark-cairo-nodes`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by princeibs** [comment]
Completed by #8
