### ISSUE TITLE
Implement Unsubscription Service for Auto-Swap

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-backend#3]
## Overview

This service processes unsubscription events for users opting out of auto-swap for a specific token.

## Payload
The service should handle incoming payloads with the following fields:

- `wallet_address` : The user's wallet address.
- `from_token` : The token they want to unsubscribe from.

## Functionality
- Remove the corresponding entry from the `swap_subscription_from_token` table.

## Acceptance Criteria
- The specified `from_token` for the given `wallet_address` is removed from the database.
- Deletion does not affect other tokens or subscriptions.

## Examples
**Input Payload:**

```json
{
  "wallet_address": "0xUserAddress",
  "from_token": "STRK"
}
```

**Database Operation:**

- Delete entry where:
    - `wallet_address` = 0xUserAddress
    - `from_token` = STRK
### Dependencies
- Unsubscription event from the smart contract.
- Database table: `swap_subscription_from_token`.

**Comment by 0xdevcollins** [comment]
I’d like to resolve this.

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by GideonBature** [comment]
Can I jump on this task?

my name is Gideon Bature, a Software Engineer with experience working on Rust projects. If assigned this task, will send my first PR within 48 hours.

Thank you!

**Comment by mimisavage** [comment]
I'd be happy to do this.

**Comment by CEOliam** [comment]
May I take this issue on?

**Comment by Michaelkingsdev** [comment]
Could I try solving this?

**Comment by Benjtalkshow** [comment]
Mind if I try this one?

**Comment by Jagadeeshftw** [comment]
I would like to work on this issue, I'm proficient in Rust, Cairo

**Comment by MrRoudyk** [comment]
Could I take over this issue?

**Comment by stevencartavia** [comment]
Hello, I would like to work on this! 

I have contributed to projects like: kakarot-rpc, raito, shinigami, cairo-lint, madara. 

I would start by start by creating an API endpoint that accepts unsubscription requests with the user’s wallet_address and the from_token they want to unsubscribe from. Then, validating the inputs and ensuring other subscriptions remain unaffected.
