### ISSUE TITLE
Implement Update Percentage Service

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-backend#4]
## Overview
This service handles events emitted when a user updates the percentage for auto-swap from a specific token.

##Payload
The service should handle incoming payloads with the following structure:

- `wallet_address` : The user's wallet address.
- `from_token` : The token for which the percentage is being updated.
- `percentage` : The new percentage value.

## Functionality
- Update the `percentage` value for the specified `from_token` in the `swap_subscription_from_token` table.

## Acceptance Criteria
- The `percentage` for the specified `from_token` is updated correctly.

## Examples
**Input Payload:**

```json
{
  "wallet_address": "0xUserAddress",
  "from_token": "STRK",
  "percentage": 75
}
```
**Database Update:**

- Update entry where:
    - `wallet_address` = 0xUserAddress
    - `from_token` = STRK
    - Set `percentage` = 75

## Dependencies
- Percentage update event from the smart contract.
- Database table: `swap_subscription_from_token`.

**Comment by 0xdevcollins** [comment]
May I take this issue on?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by GideonBature** [comment]
I'd love to work on this!

my name is Gideon Bature, a Software Engineer with experience working on Rust projects. If assigned this task, will send my first PR within 48 hours.

Thank you!

**Comment by chigozzdevv** [comment]
Hey, I understand the issue well. Please give me a chance to implement a callback for handling events emitted on percentage change.

**Comment by Birdmannn** [comment]
I al a good rust Dev. I can handle this

**Comment by CEOliam** [comment]
May I handle this issue?

**Comment by Michaelkingsdev** [comment]
I'd like to handle this task.

**Comment by Benjtalkshow** [comment]
May I pick this up?

**Comment by vestor-dev** [comment]
I'd like to handle this task.
@Abeeujah please kindly assign

**Comment by Ekene001** [comment]
I’d like to resolve this.

here's how i'll tackle this task:

To tackle this task, I will develop a service that processes events when a user updates their auto-swap percentage for a specific token. The service will receive payloads containing the wallet address, the token being updated, and the new percentage value. I will validate the incoming data to ensure it is complete and accurate. Then, I will update the swap_subscription_from_token table by matching the wallet address and token and setting the new percentage value. To ensure reliability, I will implement error handling for scenarios such as invalid tokens or database issues. After completing the implementation, I will thoroughly test the service to confirm it correctly updates the percentage and handles all edge cases, ensuring the system functions as expected.

**Comment by mimisavage** [comment]
I'd love to work on this!

**Comment by 1nonlypiece** [comment]
Hello @sprtd, I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by GideonBature** [comment]
@Abeeujah I'd love to work on this!

my name is Gideon Bature, a Software Engineer with experience working on Rust projects including web applications. If assigned this task, will send my first PR within 48 hours.

Thank you!

**Comment by Birdmannn** [comment]
I didn't get a notification when assigned this issue

**Comment by No-bodyq** [comment]
Can I work on this @sprtd

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
I'd love to work on this!

**Comment by Supa-mega** [comment]
I’m interested in this one.

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Reactjs, Nextjs, tailwindcss, Express.js, and recently exploring Cairo and rust for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to work on this issue

**Comment by suhas-sensei** [comment]
May I pick this up? "I'll implement the auto-swap percentage update service to handle events and update the swap_subscription_from_token table. 
Having experience with event handlers and database operations in previous personal projects, I'll ensure proper validation and atomic updates for user swap preferences.

**Comment by caxtonacollins** [comment]
Can I handle this task?

**Comment by DuendexCR** [comment]
Could I take over this issue?

**Comment by sprtd** [comment]
> May I pick this up? "I'll implement the auto-swap percentage update service to handle events and update the swap_subscription_from_token table. Having experience with event handlers and database operations in previous personal projects, I'll ensure proper validation and atomic updates for user swap preferences.

@suhas-sensei  You have been assigned. If you encounter issues, please feel free to [reach out](https://t.me/+PJfVLZUFylFjZDhk)

**Comment by suhas-sensei** [comment]
sure, thank you for the assignment @sprtd
