### ISSUE TITLE
Implement Transaction Logging Service

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-backend#5]
## Overview
This service logs all swap transactions for record-keeping and analytics purposes.

## Payload
The service should handle incoming payloads with the following structure:

- `wallet_address` : The user's wallet address.
- `from_token` : The token swapped from.
- `to_token` : The token swapped to.
- `percentage` : The percentage of the `from_token` swapped.
- `amount_from` : The amount of `from_token` swapped.
- `amount_to` : The amount of `to_token` received.

## Functionality
- Record the transaction in the transactions_log table.
- Ensure data integrity (e.g., valid tokens and amounts).

## Acceptance Criteria
- All transaction data is logged accurately.

## Examples
**Input Payload:**

```json
{
  "wallet_address": "0xUserAddress",
  "from_token": "STRK",
  "to_token": "USDT",
  "percentage": 50,
  "amount_from": 500,
  "amount_to": 480
}
```
**Database Insert:**

- Insert into transactions_log:
- `wallet_address`: 0xUserAddress
- `from_token`: STRK
- `to_token`: USDT
- `percentage`: 50
- `amount_from`: 500
- `amount_to`: 480

## Dependencies
- Swap event from the smart contract.
- Database table: `transactions_log`.

**Comment by GideonBature** [comment]
I'd like to handle this task.

my name is Gideon Bature, a Software Engineer with experience working on Rust projects. If assigned this task, will send my first PR within 48 hours.

Thank you!

**Comment by Birdmannn** [comment]
Could I be assigned to this?

**Comment by Michaelkingsdev** [comment]
May I take care of this?

**Comment by MrRoudyk** [comment]
Mind if I take this issue?

**Comment by vestor-dev** [comment]
Would love to tackle this!
@Abeeujah kindly assign :)

**Comment by Benjtalkshow** [comment]
Would love to tackle this!

**Comment by Ekene001** [comment]
Hi, Can i handle this task? This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. 

here's how i'll handle tackle this issue:
I will create a backend service to log swap transactions accurately. The service will validate payloads containing details like wallet_address, from_token, to_token, percentage, amount_from, and amount_to before recording them in the transactions_log table. I’ll ensure proper data validation, error handling, and seamless integration with the database and swap event triggers.

**Comment by Jagadeeshftw** [comment]
Can I start working on this?

**Comment by mimisavage** [comment]
Can I work on this, please?

**Comment by codebestia** [comment]
Can i work on this?

I am a blockchain developer with expertise in rust and i am confident in resolving this as i have worked on similar issues.

## How i will tackle this?

- I will review the payload structure and ensure proper handling of token.
- I will create a transactions_log table with fields: wallet_address, from_token, to_token, percentage, amount_from, amount_to, timestamp.
- Implement a service to receive and parse incoming payloads.Test the service with various scenarios, including edge cases 
- I will validate the payload data for correctness
- I will insert valid data into the transactions_log table and handle errors properly.
- I will set up the service to listen for swap events emitted by the smart contract, extract the details and forward it to the transaction_log service
- I will implement checks to ensure data integrity e.g percentage correctness
- I will test the service with various scenarios, including edge cases. like invalid token and invalid amount

**Comment by Supa-mega** [comment]
Let me try this one!
