### ISSUE TITLE
Implement Activity Log Retrieval

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-backend#6]
## Overview
This service enables the frontend to display recent transactions for users, supporting cursor-based pagination.

## Payload
The service should handle requests with:

- `cursor` : A pointer to the last retrieved transaction (optional).

## Functionality
- Query the `transactions_log` table, ordered by time, with support for pagination.
- Return transaction data for display on the frontend.

## Acceptance Criteria
- Transactions are retrieved in order of recency.
- Pagination works as expected, with consistent `cursor` management.

## Examples
**Request:**

```json
{
  "cursor": "2024-11-24T10:30:00Z",
  "limit": 5
}
```
**Response:**

```json
{
  "transactions": [
    {
      "wallet_address": "0xUser1",
      "from_token": "STRK",
      "to_token": "USDT",
      "amount_from": 500,
      "amount_to": 480,
      "created_at": "2024-11-24T10:29:00Z"
    },
    ...
  ],
  "next_cursor": "2024-11-24T10:25:00Z"
}
```

## Dependencies
- Frontend requirements.
- Database table: `transactions_log`.

**Comment by chigozzdevv** [comment]
Hello, please can I take this issue?

**Comment by Birdmannn** [comment]
Hello, please can I tackle this issue?

**Comment by CEOliam** [comment]
May I take care of this?

**Comment by anonfedora** [comment]
Hi, I'm Eleazar, a fullstack Blockchain developer (backend heavy), I can implement this feature.

**Comment by Michaelkingsdev** [comment]
May I take care of this?

**Comment by Benjtalkshow** [comment]
Can I take this from here?

**Comment by vestor-dev** [comment]
May I take this issue on?
@Abeeujah please kindly assign

**Comment by RichoKD** [comment]
Can I try this?

**Comment by Ekene001** [comment]
Hi, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

Here's how i will tackle the task: I will implement a backend service to display recent transactions for users, ensuring smooth cursor-based pagination. First, I will query the transactions_log table to retrieve transactions ordered by recency. The service will accept a cursor as an optional parameter to define the starting point and a limit for the number of transactions to fetch.

I will ensure the response includes the requested transactions and a next_cursor for navigating to the next set of records. To handle various scenarios, I will implement validation for input parameters, manage cases where there are no more transactions to fetch, and handle errors effectively. Additionally, I will work closely with the frontend team to ensure the service integrates seamlessly and aligns with their display requirements. Finally, I will test the service to confirm the pagination works correctly and delivers a user-friendly experience.

**Comment by Jagadeeshftw** [comment]
Let me try this one!

**Comment by MrRoudyk** [comment]
May I try my hand at this?

**Comment by mimisavage** [comment]
I’m interested in this one.

**Comment by Supa-mega** [comment]
Could I take on this issue?

**Comment by aniruddhaaps** [comment]
To address this issue, I would add:
1. Service Logic: Select transactions_log table by created_at for cursor-based pagination. The query would be something like below:

sql
Copy code
SELECT * FROM transactions_log
WHERE created_at < $cursor
ORDER BY created_at DESC
LIMIT $limit;
Return the results and the created_at of the last record as next_cursor.

2. API Endpoint: Create a GET /transactions endpoint, accepts cursor and limit as query parameters. Return paginated transaction data in the required format.

3. Testing: Transactions should be ordered by recency, and next_cursor should work seamlessly for pagination.
